sudo: required
dist: trusty

language: d

d:
 - dmd-2.071.2

# Ruby is needed to build the Jekyll docs
before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y ruby

after_success:
 - cd docs && ./deploy
